[package]
name = "win32_cacao_cornell_box"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.win32_cacao_cornell_box]
type = "executable"
entry = "src/main.vyx"
include_paths = ["../sdl3_imgui_vulkan/third_party/SDL3/include"]
lib_paths = ["E:/Dev/C++/Cacao/cmake-build-debug", "../sdl3_imgui_vulkan/third_party/SDL3/lib/x64"]
libs = ["Cacao", "SDL3"]
postbuild = ["vyx: hooks/copy_runtime_dlls.vyx"]
