[package]
name = "app"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
vyxflags = ["-O2"]

[dependencies]
core = { path = "std:core", target = "std_core" }
collections = { path = "std:collections", target = "std_collections" }

[target.app]
type = "executable"
entry = "src/main.vyx"
auto_sources = false