[package]
name = "dyn_iface_method"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.dyn_iface_method]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/component.vyx",
    "src/runner.vyx",
    "src/main.vyx"
]
