[package]
name = "dci_cpp_ecosystem"
version = "0.1.0"
entry = "main.vyx"

[build]
threads = 1
cache_dir = ".cache"
output_dir = "target"

[target.dci_cpp_ecosystem]
type = "executable"
entry = "main.vyx"
dci_stub_backend = "direct"
lib_paths = ["../../../Zyn/vendor/ICU/lib/x64"]
libs = ["icuuc78"]
