[package]
name = "manifest_windows_native"
version = "0.1.0"
entry = "src/native.vyx"

[target.native]
type = "source"
entry = "src/native.vyx"
sources = ["src/native.vyx"]

[target.native.link]
public_lib_paths_windows = ["../lib"]
public_libs_windows = ["libcurl", "libssl.lib"]
