[package]
name = "system_lib_discovery"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.system_lib_discovery]
type = "executable"
entry = "src/main.vyx"

[target.system_lib_discovery.link]
libs_windows = ["curl", "ssl", "crypto"]
