[package]
name = "vyx_runtime"
version = "0.1.0"
entry = "src/vyx_runtime.vyx"

[build]
cache_dir = ".cache"
output_dir = "out"
vyxflags = ["-O2"]

[target.vyx_runtime]
type = "static"
entry = "src/vyx_runtime.vyx"
sources = ["src/vyx_string_search.c"]
