[package]
name = "mini_app"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 0

[dependencies]
core = { path = "std:core", target = "std_core" }
collections = { path = "std:collections", target = "std_collections" }

[target.mini_app]
type = "executable"
entry = "src/main.vyx"
sources = ["src/inventory.vyx"]
auto_sources = false
