[package]
name = "import_alias_param"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.import_alias_param]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/atlas.vyx",
    "src/text.vyx",
    "src/canvas.vyx",
    "src/main.vyx"
]
