[package]
name = "mod_type_same_name"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.mod_type_same_name]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/graph.vyx",
    "src/canvas.vyx",
    "src/main.vyx"
]
