[package]
name = "dci_rust_ecosystem"
version = "0.1.0"
entry = "main.vyx"

[build]
cache_dir = ".cache/vyx"
output_dir = "target"
threads = 1

[target.dci_rust_ecosystem]
type = "executable"
entry = "main.vyx"
dci_stub_backend = "rustc"
