[package]
name = "zyn_platform_manual_smoke"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[dependencies]
Zyn = "../../../Zyn"

[target.zyn_platform_manual_smoke]
type = "executable"
entry = "src/main.vyx"
lib_paths = ["../sdl3_imgui_vulkan/third_party/SDL3/lib/x64"]
libs = ["SDL3"]
