[package]
name = "zyn_todolist_app"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.zyn_todolist_app]
type = "executable"
entry = "src/main.vyx"
lib_paths = ["../../../Zyn/out", "../../../Zyn/vendor/SDL3/lib/x64", "../../../Zyn/vendor/Cacao/lib/x64"]
libs = ["Zyn", "SDL3", "Cacao"]
postbuild = ["vyx: hooks/copy_zyn_dll.vyx"]

[zyn.app]
name = "Task Deck"
version = "0.1.0"
id = "dev.vyx.zyn.task_deck"
entry = "src/main.vyx"

[zyn.publish]
dist = "dist"
targets = ["windows-x64", "android-arm64"]

[zyn.publish.android]
project = "android"
compile_sdk = "35"
min_sdk = "23"
target_sdk = "35"
native_name = "zyn_todolist_app"
