[package]
name = "ns_alias_wins"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.ns_alias_wins]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/left.vyx",
    "src/right.vyx",
    "src/main.vyx"
]
