[package]
name = "result_err_field"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 1

[target.result_err_field]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/err.vyx",
    "src/win.vyx",
    "src/main.vyx"
]
