package com.vyx.plugin

import com.intellij.execution.RunManager
import com.intellij.execution.configurations.ConfigurationTypeUtil
import com.intellij.facet.ui.ValidationResult
import com.intellij.ide.util.projectWizard.AbstractNewProjectStep
import com.intellij.ide.util.projectWizard.CustomStepProjectGenerator
import com.intellij.ide.util.projectWizard.ProjectSettingsStepBase
import com.intellij.ide.util.projectWizard.SettingsStep
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory
import com.intellij.openapi.module.Module
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.TextFieldWithBrowseButton
import com.intellij.openapi.ui.ValidationInfo
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.openapi.wm.impl.welcomeScreen.AbstractActionWithPanel
import com.intellij.platform.DirectoryProjectGeneratorBase
import com.intellij.platform.GeneratorPeerImpl
import com.intellij.platform.ProjectGeneratorPeer
import com.intellij.ui.components.JBCheckBox
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBTextField
import java.awt.BorderLayout
import java.awt.GridBagConstraints
import java.awt.GridBagLayout
import java.awt.Insets
import java.io.File
import javax.swing.*

/**
 * File → New → Project → Vyx
 *
 * CLion / New Project dialog uses [CustomStepProjectGenerator.createStep] and then
 * [ProjectGeneratorPeer.getComponent]. [buildUI] is only used for WebProjectTemplate
 * peers, so the settings UI must live in getComponent (Rust plugin pattern).
 */
class VyxProjectGenerator :
    DirectoryProjectGeneratorBase<VyxProjectSettings>(),
    CustomStepProjectGenerator<VyxProjectSettings> {

    override fun getName(): String = "Vyx"

    override fun getDescription(): String =
        "Create a Vyx project (application or library) with toolchain, Vyx.toml, and run configuration."

    override fun getLogo(): Icon = VyxIcons.Vyx

    override fun createPeer(): ProjectGeneratorPeer<VyxProjectSettings> = VyxProjectGeneratorPeer()

    override fun createStep(
        projectGenerator: com.intellij.platform.DirectoryProjectGenerator<VyxProjectSettings>,
        callback: AbstractNewProjectStep.AbstractCallback<VyxProjectSettings>
    ): AbstractActionWithPanel {
        // Same as Rust: ProjectSettingsStepBase with a fresh AbstractCallback.
        // Host may pass its own callback; we keep a working create button path either way.
        return ProjectSettingsStepBase(projectGenerator, AbstractNewProjectStep.AbstractCallback())
    }

    override fun validate(baseDirPath: String): ValidationResult {
        if (baseDirPath.isBlank()) return ValidationResult("Project location is empty")
        return ValidationResult.OK
    }

    override fun generateProject(
        project: Project,
        baseDir: VirtualFile,
        settings: VyxProjectSettings,
        module: Module
    ) {
        val root = File(baseDir.path)
        val name = settings.packageName.ifBlank {
            root.name.ifBlank { "hello" }
        }.replace(Regex("[^A-Za-z0-9_\\-]"), "_")

        val kind = settings.kind
        File(root, "src").mkdirs()

        File(root, "Vyx.toml").writeText(buildToml(name, kind))
        writeSources(root, name, kind)

        if (settings.createGitignore) {
            File(root, ".gitignore").writeText(
                """
                out/
                .cache/
                *.obj
                *.o
                *.exe
                *.dll
                *.lib
                *.a
                *.so
                *.dylib
                .idea/
                """.trimIndent() + "\n"
            )
        }

        if (settings.createReadme) {
            File(root, "README.md").writeText(buildReadme(name, kind))
        }

        val projectSettings = VyxSettings.getInstance(project)
        val appSettings = VyxApplicationSettings.getInstance()
        val chosenVyxc = settings.vyxcPath.trim()
        if (chosenVyxc.isNotEmpty()) {
            projectSettings.vyxcPath = chosenVyxc
            if (appSettings.vyxcPath.isBlank()) {
                appSettings.vyxcPath = chosenVyxc
            }
        } else if (projectSettings.vyxcPath.isBlank() && appSettings.vyxcPath.isNotBlank()) {
            projectSettings.vyxcPath = appSettings.vyxcPath
        }

        baseDir.refresh(false, true)

        if (settings.createRunConfiguration) {
            ApplicationManager.getApplication().invokeLater {
                createDefaultRunConfigurations(project, root, name, kind)
            }
        }
    }

    private fun buildToml(name: String, kind: VyxProjectSettings.Kind): String = buildString {
        appendLine("# Vyx project generated by the Vyx IDEA plugin")
        appendLine()
        appendLine("[package]")
        appendLine("name = \"$name\"")
        appendLine("version = \"0.1.0\"")
        appendLine("entry = \"${kind.entryFile}\"")
        appendLine()
        appendLine("[build]")
        appendLine("output_dir = \"out\"")
        appendLine("cache_dir = \".cache\"")
        appendLine()
        appendLine("[target.$name]")
        appendLine("type = \"${kind.tomlType}\"")
        appendLine("entry = \"${kind.entryFile}\"")
        appendLine()
    }

    private fun writeSources(root: File, name: String, kind: VyxProjectSettings.Kind) {
        when (kind) {
            VyxProjectSettings.Kind.APPLICATION -> {
                File(root, "src/main.vyx").writeText(
                    """
                    module $name;

                    fn main() {
                        print("Hello, Vyx!");
                    }
                    """.trimIndent() + "\n"
                )
            }
            VyxProjectSettings.Kind.LIBRARY_STATIC,
            VyxProjectSettings.Kind.LIBRARY_SHARED -> {
                File(root, "src/lib.vyx").writeText(
                    """
                    module $name;

                    public fn greet(who: string) -> string {
                        return "Hello, " + who + "!";
                    }
                    """.trimIndent() + "\n"
                )
            }
        }
    }

    private fun buildReadme(name: String, kind: VyxProjectSettings.Kind): String = buildString {
        appendLine("# $name")
        appendLine()
        appendLine("Vyx **${kind.label}** project.")
        appendLine()
        appendLine("## Build")
        appendLine()
        appendLine("```bash")
        appendLine("vyxc build")
        appendLine("```")
        appendLine()
        if (!kind.isLibrary) {
            appendLine("## Run")
            appendLine()
            appendLine("```bash")
            appendLine("vyxc --run ${kind.entryFile}")
            appendLine("# or after build:")
            appendLine("out/$name")
            appendLine("```")
            appendLine()
        }
        appendLine("## Toolchain")
        appendLine()
        appendLine("IDE resolution: **1 user path → 2 plugin install dir → 3 PATH**.")
        appendLine("Settings → Languages & Frameworks → **Vyx**.")
        appendLine()
    }

    private fun createDefaultRunConfigurations(
        project: Project,
        root: File,
        name: String,
        kind: VyxProjectSettings.Kind
    ) {
        val runManager = RunManager.getInstance(project)
        val type = ConfigurationTypeUtil.findConfigurationType(VyxConfigurationType::class.java) ?: return

        val factories = type.configurationFactories
        val singleFactory = factories.firstOrNull { it.id == "VYX_SINGLE" } ?: return
        val projectFactory = factories.firstOrNull { it.id == "VYX_PROJECT" } ?: singleFactory

        fun addIfMissing(
            displayName: String,
            factory: com.intellij.execution.configurations.ConfigurationFactory,
            configure: (VyxRunConfig) -> Unit
        ) {
            if (runManager.findConfigurationByTypeAndName(type, displayName) != null) return
            val settings = runManager.createConfiguration(displayName, factory)
            val cfg = settings.configuration as? VyxRunConfig ?: return
            configure(cfg)
            runManager.addConfiguration(settings)
            if (runManager.selectedConfiguration == null ||
                runManager.selectedConfiguration?.type !is VyxConfigurationType
            ) {
                runManager.selectedConfiguration = settings
            }
        }

        if (!kind.isLibrary) {
            val mainFile = File(root, "src/main.vyx").absolutePath
            addIfMissing("Run $name", singleFactory) { cfg ->
                cfg.mode = VyxRunConfig.Mode.RUN_FILE
                cfg.scriptPath = mainFile
                cfg.workDir = root.absolutePath
                cfg.targetName = name
            }
            addIfMissing("Build & Run $name", projectFactory) { cfg ->
                cfg.mode = VyxRunConfig.Mode.BUILD_AND_RUN
                cfg.scriptPath = mainFile
                cfg.workDir = root.absolutePath
                cfg.targetName = name
            }
        } else {
            addIfMissing("Build $name", projectFactory) { cfg ->
                cfg.mode = VyxRunConfig.Mode.BUILD_AND_RUN
                cfg.workDir = root.absolutePath
                cfg.targetName = name
            }
        }
    }
}

/**
 * Peer used by ProjectSettingsStepBase.
 * Critical: return a real settings panel from [getComponent] — CLion calls that,
 * not [buildUI] (buildUI is only for WebProjectTemplate peers).
 */
class VyxProjectGeneratorPeer : GeneratorPeerImpl<VyxProjectSettings>(
    VyxProjectSettings(),
    JPanel(BorderLayout())
) {
    private val nameField = JBTextField("hello")
    private val kindList = JList(VyxProjectSettings.Kind.values()).apply {
        selectionMode = ListSelectionModel.SINGLE_SELECTION
        selectedIndex = 0
        visibleRowCount = 4
        cellRenderer = object : DefaultListCellRenderer() {
            override fun getListCellRendererComponent(
                list: JList<*>?,
                value: Any?,
                index: Int,
                isSelected: Boolean,
                cellHasFocus: Boolean
            ): java.awt.Component {
                val c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus) as JLabel
                if (value is VyxProjectSettings.Kind) {
                    c.text = value.label
                    c.icon = VyxIcons.Vyx
                }
                return c
            }
        }
    }
    private val gitignoreBox = JBCheckBox("Create .gitignore", true)
    private val readmeBox = JBCheckBox("Create README.md", true)
    private val runConfigBox = JBCheckBox("Create run configuration", true)
    private val vyxcField = TextFieldWithBrowseButton()
    private val resolvedLabel = JBLabel()
    private val panel: JPanel = JPanel(GridBagLayout())
    private var checkValid: Runnable? = null

    init {
        val app = VyxApplicationSettings.getInstance()
        val defaultVyxc = app.vyxcPath.ifBlank {
            VyxToolPaths.resolve("", "vyxc")
        }
        if (defaultVyxc.contains(File.separatorChar) || defaultVyxc.contains('/') || File(defaultVyxc).isAbsolute) {
            if (File(defaultVyxc).exists() || app.vyxcPath.isNotBlank()) {
                vyxcField.text = if (app.vyxcPath.isNotBlank()) app.vyxcPath else defaultVyxc
            }
        } else if (app.vyxcPath.isNotBlank()) {
            vyxcField.text = app.vyxcPath
        }

        vyxcField.addBrowseFolderListener(
            "Select vyxc",
            "Compiler / toolchain executable (stored in project + default settings)",
            null,
            FileChooserDescriptorFactory.createSingleFileDescriptor()
        )
        vyxcField.textField.document.addDocumentListener(object : javax.swing.event.DocumentListener {
            override fun insertUpdate(e: javax.swing.event.DocumentEvent?) {
                refreshResolved()
                checkValid?.run()
            }
            override fun removeUpdate(e: javax.swing.event.DocumentEvent?) {
                refreshResolved()
                checkValid?.run()
            }
            override fun changedUpdate(e: javax.swing.event.DocumentEvent?) {
                refreshResolved()
                checkValid?.run()
            }
        })
        nameField.document.addDocumentListener(object : javax.swing.event.DocumentListener {
            override fun insertUpdate(e: javax.swing.event.DocumentEvent?) { checkValid?.run() }
            override fun removeUpdate(e: javax.swing.event.DocumentEvent?) { checkValid?.run() }
            override fun changedUpdate(e: javax.swing.event.DocumentEvent?) { checkValid?.run() }
        })
        kindList.addListSelectionListener { checkValid?.run() }

        val gbc = GridBagConstraints().apply {
            fill = GridBagConstraints.HORIZONTAL
            insets = Insets(4, 4, 4, 4)
            anchor = GridBagConstraints.WEST
        }
        var row = 0
        fun addRow(label: String, comp: JComponent, fillBoth: Boolean = false) {
            gbc.gridy = row
            gbc.gridx = 0
            gbc.weightx = 0.0
            gbc.weighty = 0.0
            gbc.gridwidth = 1
            gbc.fill = GridBagConstraints.HORIZONTAL
            panel.add(JLabel(label), gbc)
            gbc.gridx = 1
            gbc.weightx = 1.0
            if (fillBoth) {
                gbc.weighty = 1.0
                gbc.fill = GridBagConstraints.BOTH
            }
            panel.add(comp, gbc)
            row++
        }

        addRow("Package name:", nameField)
        addRow("Toolchain (vyxc):", vyxcField)
        gbc.gridy = row
        gbc.gridx = 0
        gbc.gridwidth = 2
        gbc.weightx = 1.0
        gbc.weighty = 0.0
        gbc.fill = GridBagConstraints.HORIZONTAL
        resolvedLabel.foreground = java.awt.Color.GRAY
        panel.add(resolvedLabel, gbc)
        row++

        gbc.gridy = row
        gbc.gridx = 0
        gbc.gridwidth = 2
        panel.add(JLabel("Project template:"), gbc)
        row++
        gbc.gridy = row
        gbc.weighty = 1.0
        gbc.fill = GridBagConstraints.BOTH
        panel.add(JScrollPane(kindList), gbc)
        row++

        gbc.gridy = row
        gbc.weighty = 0.0
        gbc.fill = GridBagConstraints.HORIZONTAL
        panel.add(runConfigBox, gbc)
        row++
        gbc.gridy = row
        panel.add(gitignoreBox, gbc)
        row++
        gbc.gridy = row
        panel.add(readmeBox, gbc)
        row++

        gbc.gridy = row
        panel.add(
            JLabel(
                "<html><body style='width:320px;color:gray'>" +
                    "Toolchain empty → use Settings / plugin dir / PATH. " +
                    "Value written to project Vyx settings; empty global default is filled too." +
                    "</body></html>"
            ),
            gbc
        )

        // Put our form into the component owned by GeneratorPeerImpl
        (super.getComponent() as JPanel).apply {
            removeAll()
            layout = BorderLayout()
            add(panel, BorderLayout.CENTER)
        }

        refreshResolved()
    }

    private fun refreshResolved() {
        val resolved = VyxToolPaths.resolve(vyxcField.text, "vyxc")
        resolvedLabel.text = "Resolved: $resolved"
    }

    override fun getComponent(
        myLocationField: TextFieldWithBrowseButton,
        checkValid: Runnable
    ): JComponent {
        this.checkValid = checkValid
        return getComponent()
    }

    override fun getComponent(): JComponent {
        // GeneratorPeerImpl stores the panel we filled in init
        return super.getComponent()
    }

    override fun buildUI(settingsStep: SettingsStep) {
        // Not used by CLion for non-web generators, but keep as fallback.
        settingsStep.addSettingsField("Package name:", nameField)
        settingsStep.addSettingsField("Toolchain (vyxc):", vyxcField)
        settingsStep.addSettingsField("Project template:", JScrollPane(kindList))
        settingsStep.addSettingsComponent(runConfigBox)
        settingsStep.addSettingsComponent(gitignoreBox)
        settingsStep.addSettingsComponent(readmeBox)
        settingsStep.addSettingsComponent(resolvedLabel)
    }

    override fun getSettings(): VyxProjectSettings {
        val kind = kindList.selectedValue ?: VyxProjectSettings.Kind.APPLICATION
        return VyxProjectSettings(
            packageName = nameField.text.trim().ifBlank { "hello" },
            kind = kind,
            createGitignore = gitignoreBox.isSelected,
            createReadme = readmeBox.isSelected,
            vyxcPath = vyxcField.text.trim(),
            createRunConfiguration = runConfigBox.isSelected
        )
    }

    override fun validate(): ValidationInfo? {
        val n = nameField.text.trim()
        if (n.isEmpty()) return ValidationInfo("Package name is required", nameField)
        if (!n.matches(Regex("[A-Za-z_][A-Za-z0-9_\\-]*"))) {
            return ValidationInfo("Use letters, digits, underscore, hyphen", nameField)
        }
        if (kindList.selectedValue == null) {
            return ValidationInfo("Select a project template", kindList)
        }
        return null
    }
}