[package]
name = "zyn_canvas_view_smoke"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[dependencies]
Zyn = "../../../Zyn"

[target.zyn_canvas_view_smoke]
type = "executable"
entry = "src/main.vyx"
lib_paths = ["../../../Zyn/out", "../../../Zyn/vendor/SDL3/lib/x64", "../../../Zyn/vendor/Cacao/lib/x64"]
libs = ["Zyn", "SDL3", "Cacao"]
