[package]
name = "vec_dyn_peer"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 1

[target.vec_dyn_peer]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/view.vyx",
    "src/comp.vyx",
    "src/main.vyx"
]
