[package]
name = "dci_qt"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 1

[target.dci_qt]
type = "executable"
entry = "src/main.vyx"
dci_stub_backend = "clang-cpp"
cxx = "${DCI_QT_CXX}"
include_paths = [
    "native",
    "${DCI_QT_INCLUDE}",
    "${DCI_QT_INCLUDE_QTCORE}",
    "${DCI_QT_MKSPECS}",
]
cxxflags = [
    "-std=c++17",
    "-fms-compatibility",
    "-DQT_CORE_LIB",
    "-DUNICODE",
    "-D_UNICODE",
    "-DWIN32",
    "-D_WIN64",
]
lib_paths = [
    "${DCI_QT_LIBDIR}",
]
libs = [
    "Qt6Core",
]

