[package]
name = "same_mod_static"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.same_mod_static]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/event.vyx",
    "src/peer.vyx",
    "src/child.vyx",
    "src/main.vyx"
]
