[package]
name = "host_dyn_scene"
version = "0.1.0"
entry = "src/main.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 1

[target.host_dyn_scene]
type = "executable"
entry = "src/main.vyx"
sources = [
    "src/scene.vyx",
    "src/main.vyx"
]
