[package]
name = "cacao_binding_smoke"
version = "0.1.0"
entry = "src/typed.vyx"

[build]
cache_dir = ".cache"
output_dir = "target"
threads = 2

[target.typed]
type = "executable"
entry = "src/typed.vyx"
lib_paths = ["E:/Dev/C++/Cacao/cmake-build-debug"]
libs = ["Cacao"]
postbuild = ["vyx: hooks/copy_cacao_dll.vyx"]

[target.full]
type = "executable"
entry = "src/full.vyx"
lib_paths = ["E:/Dev/C++/Cacao/cmake-build-debug"]
libs = ["Cacao"]
postbuild = ["vyx: hooks/copy_cacao_dll.vyx"]

[target.rt]
type = "executable"
entry = "src/rt.vyx"
lib_paths = ["E:/Dev/C++/Cacao/cmake-build-debug"]
libs = ["Cacao"]
postbuild = ["vyx: hooks/copy_cacao_dll.vyx"]

[target.compute]
type = "executable"
entry = "src/compute.vyx"
lib_paths = ["E:/Dev/C++/Cacao/cmake-build-debug"]
libs = ["Cacao"]
postbuild = ["vyx: hooks/copy_cacao_dll.vyx"]

[target.query_sync]
type = "executable"
entry = "src/query_sync.vyx"
lib_paths = ["E:/Dev/C++/Cacao/cmake-build-debug"]
libs = ["Cacao"]
postbuild = ["vyx: hooks/copy_cacao_dll.vyx"]

[target.queue_lifetime]
type = "executable"
entry = "src/queue_lifetime.vyx"
lib_paths = ["E:/Dev/C++/Cacao/cmake-build-debug"]
libs = ["Cacao"]
postbuild = ["vyx: hooks/copy_cacao_dll.vyx"]
