[package]
name = "BoxFactory"
version = "0.1.0"
entry = "src/native.vyx"

[build]
cache_dir = ".cache"
output_dir = "out"
threads = 2

[dependencies]
BoxAbi = "../dep"

[target.BoxFactory]
type = "shared"
entry = "src/native.vyx"
