[package]
name = "BoxAbi"
version = "0.1.0"
entry = "src/api.vyx"

[build]
cache_dir = ".cache"
output_dir = "out"
threads = 2
mir_partition = true

[target.BoxAbi]
type = "shared"
entry = "src/api.vyx"
sources = ["src/world.vyx", "src/clone.vyx", "src/apply.vyx"]
